name: Run Tests and send coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: STAGING

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn clean install

    - name: Codacy Coverage Reporter
      shell: bash
      run: |
        export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}                                                         ok 
        export CODACY_API_BASE_URL=${{ vars.API_BASE_URL }}
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml